#ifndef __MODEL_HLSL__
#define __MODEL_HLSL__

#include "../Shader/Normal.hlsli"
#include "../Shader/Constants.hlsli"
#include "../Shader/Dispatch.hlsli"

/**
* [EN]
* Amplification Shader payload for the static/skeletal/depth-prepass/
* material-sort AS->MS dispatches (ModelAS.hlsl/GeometryBufferAS.hlsl/
* ModelTransparentAS.hlsl/ModelSilhouetteAS.hlsl) - one surviving meshlet per
* thread group.
*/
struct ModelASPayload
{
	uint instance_index;
	uint meshlet_indices[32];
};

/**
* [EN]
* VisibilityBuffer groundwork: the G-Buffer pass PS (StaticModelPS/
* SkeletalModelPS) only needs texcoord (for the alpha-cutout clip) plus the
* id fields - world position/normal/tangent/velocity are no longer consumed
* here, so the MS doesn't compute or carry them anymore.
* Model/Material/MaterialResolveCS.hlsl recomputes all of that independently
* from (instance/meshlet/triangle) + the same raw vertex buffers.
*/
struct ModelMSOutput
{
	float4 position : SV_Position;
	float2 texcoord : TEXCOORD0;
	nointerpolation uint instance_index : BLENDINDICES0;
	nointerpolation uint meshlet_index  : BLENDINDICES1;
};

/**
* [EN]
* Per-primitive Mesh Shader output (the "primitives" array, not "vertices") -
* SV_PrimitiveID is NOT auto-generated by the mesh shader pipeline stage the
* way it is for the traditional (non-indexed-draw) pipeline, so the
* triangle-in-meshlet index has to be passed explicitly like this.
*/
struct ModelMSPrimitiveOutput
{
	nointerpolation uint triangle_in_meshlet_index : BLENDINDICES2;
};

struct ModelVSOutput
{
	float4 position : SV_Position;
	float2 texcoord : TEXCOORD0;
	nointerpolation uint instance_index : BLENDINDICES0;
	nointerpolation uint meshlet_index  : BLENDINDICES1;
	nointerpolation uint triangle_in_meshlet_index : BLENDINDICES2;
};

/**
* [EN]
* Depth prepass output. Carries texcoord + instance index so the prepass
* pixel shader can apply the same alpha-cutout clip as the G-Buffer pass;
* without it masked (alphaMode=MASK) holes write depth and occlude
* geometry behind them.
*/
struct DepthPrepassOutput
{
	float4 position : SV_Position;
	float2 texcoord : TEXCOORD0;
	nointerpolation uint instance_index : BLENDINDICES0;
};

/**
* [EN]
* Raster G-Buffer pass output - just the VisibilityBuffer id (see
* GeometryBuffer::BeginVisibility). base_color/normal/roughness/material
* extension/velocity/emissive are no longer produced here; they're
* rewritten wholesale by the material resolve compute pass
* (Model/Material/MaterialResolveCS.hlsl) from this id + depth.
*/
struct ModelPSOutput
{
	uint4 visibility_id : SV_Target0; // x: instance_index, y: pack(meshlet_index, triangle_in_meshlet_index), zw: asuint(texcoord)
};

/**
* [EN]
* Amplification Shader payload for the shell-fur forward pass
* (FurShellAS -> FurShellMS -> FurShellPS) - one surviving meshlet of one
* shell layer per thread group.
*/
struct FurShellPayload
{
	uint instance_index;
	uint shell_index;
	uint meshlet_indices[32];
};

/**
* [EN]
* Mesh Shader output for the shell-fur forward pass. shell_ratio is
* shell_index / fur_shell_count_, used by the PS to fade/shade shells
* toward the tip.
*/
struct FurShellMSOutput
{
	float4 position       : SV_Position;
	float3 world_position : TEXCOORD1;
	float3 world_normal   : TEXCOORD2;
	float3 world_tangent  : TEXCOORD3;
	float2 texcoord       : TEXCOORD0;
	nointerpolation uint instance_index : BLENDINDICES0;
	nointerpolation float shell_ratio   : TEXCOORD4;
};

/**
* [EN]
* Mesh Shader output for the OIT resolve full-screen triangle
* (Model/Transparent/OITResolveMS.hlsl -> OITResolvePS.hlsl) - position
* only, the PS walks the Per-Pixel Linked List itself from SV_Position.
*/
struct OITResolveOutput
{
	float4 position : SV_Position;
};

/**
* [EN]
* Fully expanded vertex, produced by DecodeModelVertex from a
* CompressedModelVertex. Skinning attributes live in the separate CompressedModelSkin
* buffer (skinned models only), not here.
*/
struct ExpandedModelVertex
{
	float3 position_;
	float3 normal_;
	float4 tangent_;
	float2 texcoord_;
};

/**
* [EN]
* Mirrors the C++ CompressedVertex (Model/Crister.h) - 16 bytes. Quantised
* on the CPU at upload; the encode there must match DecodeModelVertex
* exactly. position_xy_/position_z_texu_ pack position (UNORM in the
* instance's position AABB) and texcoord u (UNORM in the instance's UV
* AABB) as 16-bit fields; texv_tangent_ packs texcoord v plus an
* octahedral-encoded tangent (x:8 y:7) and its handedness sign (bit 15);
* normal_ is the octahedral-encoded normal (x:16 y:16).
*/
struct CompressedModelVertex
{
	uint position_xy_;
	uint position_z_texu_;
	uint texv_tangent_;
	uint normal_;
};

/**
* [EN]
* Mirrors the C++ CompressedSkinVertex (Model/Crister.h) - 12 bytes.
* joints_xy_/joints_zw_ pack the four influencing joint indices as 16-bit
* fields; weights_ packs their four blend weights as 8-bit UNORM.
*/
struct CompressedModelSkin
{
	uint joints_xy_;
	uint joints_zw_;
	uint weights_;
};

/**
* [EN]
* Unpacked skinning attributes, produced by DecodeSkinVertex from a
* CompressedModelSkin. weights_ is renormalised because four 8-bit UNORM
* values rarely sum to exactly one.
*/
struct ExpandedModelSkin
{
	uint4 joints_;
	float4 weights_;
};

/**
* [EN]
* One meshlet's range into the shared vertex-index/primitive-index buffers
* (ModelGeometry::vertexIndicesBufferIndex_/primitiveIndicesBufferIndex_).
*/
struct ModelMeshlet
{
	uint vertex_offset_;
	uint triangle_offset_;
	uint vertex_count_;
	uint triangle_count_;
};

/**
* [EN]
* Bounding sphere (center_/radius_) plus normal cone (cone_axis_/
* cone_cutoff_, dot-product backface test) for one meshlet, used by the
* per-meshlet culling in ModelAS.hlsl/GeometryBufferAS.hlsl/
* ModelTransparentAS.hlsl/ModelSilhouetteAS.hlsl.
*/
struct ModelMeshletBound
{
	float3 center_;
	float radius_;
	float3 cone_axis_;
	float cone_cutoff_;
};

/**
* [EN]
* Per-pixel surface rebuilt from a VisibilityBuffer-style (instance,
* meshlet, triangle-in-meshlet) triplet. Built identically by
* Model/Material/MaterialResolveCS.hlsl (deferred opaque resolve, which
* gets the triplet by unpacking the VisID texture) and
* Model/Transparent/ModelTransparentPS.hlsl (OIT accumulation, which gets
* it straight from the rasterizer), so transparent and opaque geometry is
* always shaded from identical reconstructed attributes. previous_world_position_
* is the same point through instance.transform_.previous_world_ - the
* deferred resolve needs it for motion vectors, the OIT path ignores it.
* normal_/tangent_ are world space, already flipped when the pixel lands
* on a back face.
*/
struct ModelSurface
{
	float3 world_position_;
	float3 previous_world_position_;
	float3 normal_;
	float3 tangent_;
	float tangent_sign_;
	float2 texcoord_;
};

/**
* [EN]
* Bone palette element (inverse bind matrix x joint global transform). The
* CPU stores engine Matrix (row-major, row-vector convention) via raw
* memcpy. Stored as four explicit row vectors instead of float4x4 so the
* layout does not depend on matrix-orientation annotations, which are
* unreliable inside structured buffers - see LoadBoneMatrix below.
*/
struct ModelBoneMatrix
{
	float4 row0_;
	float4 row1_;
	float4 row2_;
	float4 row3_;
};

/**
* [EN]
* One fragment in the OIT Per-Pixel Linked List (Model/Transparent/
* OITBuffer.h) - 16 bytes, must match the fragmentStride in
* Model/Transparent/OITBuffer.cpp. packed_color_rg_/packed_color_ba_ are
* the fragment's color packed by PackColor; next_ links to the next
* (further) fragment at this pixel, OIT_INVALID_INDEX for the list end.
*/
struct OITFragment
{
	uint packed_color_rg_;
	uint packed_color_ba_;
	float depth_;
	uint next_;
};

struct OitUnorderedAccessIndices
{
	uint head_pointer_index_;
	uint fragment_buffer_index_;
	uint counter_index_;
	uint oit_unordered_access_padding_0_;
};

// Mirrors the C++ ShadingModel enum (Model/Crister.h). Read from
// ModelShading::shading_model_ and switched on by
// Opaque/DeferredLightingPS.hlsl's direct-light dispatch.
#define SHADING_MODEL_PBR 0
#define SHADING_MODEL_UNLIT 1
#define SHADING_MODEL_PHONG 2
#define SHADING_MODEL_TOON 3
#define SHADING_MODEL_LAMBERT 4
#define SHADING_MODEL_FLAT 5
#define SHADING_MODEL_FUR 6

// VisibilityBuffer material sort: pixels are bucketed by (instance_index %
// MATERIAL_SORT_BUCKET_COUNT) before Model/Material/MaterialResolveCS.hlsl runs, so
// adjacent threads in a wave land on the same/nearby instance and share
// texture indices - improving control-flow coherency and texture cache
// locality versus resolving in raw screen order. 1024 is also the max
// threadgroup size, so Model/Material/MaterialPrefixSumCS.hlsl's scan fits in one
// dispatch. See Model/Material/MaterialClassifyCS.hlsl / MaterialPrefixSumCS.hlsl /
// MaterialScatterCS.hlsl.
#define MATERIAL_SORT_BUCKET_COUNT 1024
#define MATERIAL_SORT_INVALID_PIXEL 0xFFFFFFFF

// Shell-fur: the FurShell pass dispatches fur_instance_count_ * FUR_SHELL_MAX
// amplification groups; each renders one shell layer of one fur instance.
// Must match ModelRenderer's furShellMax_.
#define FUR_SHELL_MAX 32

// OIT (Order-Independent Transparency) Per-Pixel Linked List resolve:
// OIT_MAX_LAYERS is the fixed-size per-pixel array OITResolvePS.hlsl sorts
// and blends the front-most fragments into (NOT OITBuffer::poolLayers_,
// the unrelated whole-screen fragment pool budget), OIT_MAX_WALK caps how
// many linked-list fragments it walks per pixel while filling that array,
// and OIT_INVALID_INDEX marks an absent bindless index/list terminator.
#define OIT_MAX_LAYERS 8
#define OIT_MAX_WALK 32
#define OIT_INVALID_INDEX 0xFFFFFFFF

/**
* [EN]
* previous_world_ is this instance's own world matrix as of the previous
* frame - used for velocity (MaterialResolveCS.hlsl/ModelTransparentPS.hlsl)
* so moving objects get correct motion vectors instead of only reflecting
* camera motion. Per-bone skinning and morph deformation come from the
* previous-frame bone palette / morph weights instead
* (ModelShaderResourceIndices::previous_bone_matrix_index_/previous_morph_weight_index_).
*/
struct ModelTransform                     // 12 rows
{
	row_major float4x4 world_;
	row_major float4x4 inverse_transpose_world_;
	row_major float4x4 previous_world_;
};

/**
* [EN]
* Bindless SRVs of this instance's geometry buffers (compressed vertices,
* meshlets, meshlet bounds, meshlet-local vertex indices, packed primitive
* indices), plus meshlet_offset_/meshlet_count_ - this instance's range
* into the shared meshlet buffers.
*/
struct ModelGeometry                      // 2 rows
{
	uint vertex_buffer_index_;
	uint meshlet_buffer_index_;
	uint meshlet_bound_buffer_index_;
	uint vertex_indices_buffer_index_;
	uint primitive_indices_buffer_index_;
	uint meshlet_offset_;
	uint meshlet_count_;
	uint model_geometry_padding_0_;
};

/**
* [EN]
* Dequantisation AABB for CompressedModelVertex (per Crister), plus the
* cumulative screen-space LOD error of this instance's cluster and of the
* next coarser cluster in the same chain (FLT_MAX when there is none or LOD
* selection must always keep this instance).
*/
struct ModelStreaming                     // 3 rows
{
	float3 position_min_;
	float texcoord_min_u_;

	float3 position_extent_;
	float texcoord_min_v_;

	float2 texcoord_extent_;
	float lod_error_;
	float lod_error_next_;
};

/**
* [EN]
* shading_model_ selects the lighting response DeferredLightingPS.hlsl
* evaluates this instance with. fur_length_/fur_density_/fur_shell_count_
* are ShadingModel::Fur tuning (shell height in metres, per-strand
* hash-noise density, shell layers above the base surface).
*/
struct ModelShading                       // 2 rows
{
	uint shading_model_;
	float fur_length_;
	float fur_density_;
	uint fur_shell_count_;

	uint double_sided_;
	uint blend_;
	uint selected_;
	uint model_shading_padding_0_;
};

/**
* [EN]
* skin_vertex_buffer_index_ is the bindless SRV of the CompressedModelSkin
* buffer (0xFFFFFFFF for a static, unskinned instance).
*/
struct ModelSkining                       // 1 row
{
	uint skin_index_;
	uint bone_offset_;
	uint skin_vertex_buffer_index_;
	uint model_skining_padding_0_;
};

/**
* [EN]
* Raster morph blend (see the model mesh shaders and
* Model/Material/MaterialResolveCS.hlsl/Model/Transparent/ModelTransparentPS.hlsl).
* morph_delta_offset_ is in float3 units into morph_delta_buffer_index_; morph_vertex_offset_/
* morph_vertex_count_ are this SubMesh's Crister::vertices_ range start and
* ORIGINAL (pre-LOD) vertex count; morph_weight_offset_ indexes into the
* shared per-frame morph weight buffer. morph_target_count_ == 0 disables
* blending entirely - always the case for a non-morphed instance, and also
* for a morphed instance drawn from an own-page (streamed-in, non-pool)
* cluster: only the LOD 0 shared vertex pool range is index-aligned with
* morph_delta_buffer_index_/vertex_morph_source_buffer_index_'s
* crister-wide numbering (see Crister::vertexMorphSource_'s comment), so
* ModelRenderer leaves these zeroed for any other cluster and that
* instance's coarser LOD renders its frozen bind-pose shape instead of
* morphing.
*/
struct ModelMorph                         // 2 rows
{
	uint morph_delta_buffer_index_;
	uint vertex_morph_source_buffer_index_;
	uint morph_delta_offset_;
	uint morph_vertex_offset_;

	uint morph_vertex_count_;
	uint morph_target_count_;
	uint morph_weight_offset_;
	uint model_morph_padding_0_;
};

/**
* [EN]
* Base PBR values and their matching bindless texture SRVs. ior_ is
* KHR_materials_ior; emissive_strength_ is KHR_materials_emissive_strength.
* All four base textures plus occlusion_texture_index_ are sampled by
* Model/Opaque/DeferredLightingPS.hlsl using the model UV recovered from
* the VisibilityBuffer (RT4.zw) - the deferred pass has no interpolated
* texcoord of its own.
*/
struct ModelTexture                       // 5 rows
{
	float4 base_color_;
	float metallic_;
	float roughness_;
	float alpha_cutoff_;
	float ior_;

	float3 emissive_;
	float emissive_strength_;

	uint base_color_texture_index_;
	uint normal_texture_index_;
	uint metallic_roughness_texture_index_;
	uint emissive_texture_index_;

	uint occlusion_texture_index_;
	uint3 model_texture_padding_0_;
};

/**
* [EN]
* KHR extension material values/textures (specular, clearcoat, anisotropy,
* transmission, volume, sheen, iridescence, unlit). Each texture multiplies
* its matching factor per the glTF spec's channel convention; 0xFFFFFFFF
* means absent.
*/
struct ModelExtension                     // 9 rows
{
	float specular_factor_;
	float3 specular_color_;
	float clearcoat_factor_;
	float clearcoat_roughness_;
	float anisotropy_;
	float anisotropy_rotation_;
	float transmission_factor_;
	float volume_thickness_factor_;
	float volume_attenuation_distance_;
	float unlit_;
	float3 volume_attenuation_color_;
	float sheen_roughness_;
	float3 sheen_color_;
	float iridescence_factor_;
	float iridescence_ior_;
	float iridescence_thickness_;
	uint specular_texture_index_;
	uint specular_color_texture_index_;
	uint clearcoat_texture_index_;
	uint clearcoat_roughness_texture_index_;
	uint clearcoat_normal_texture_index_;
	uint transmission_texture_index_;
	uint thickness_texture_index_;
	uint sheen_color_texture_index_;
	uint sheen_roughness_texture_index_;
	uint iridescence_texture_index_;
	uint iridescence_thickness_texture_index_;
	uint anisotropy_texture_index_;
	uint2 model_extension_padding_0_;
};

/**
* [EN]
* Per-instance StructuredBuffer element read by every Model pass (depth
* prepass, shadow, G-buffer, deferred lighting, GI/reflection/refraction
* raytracing, OIT). Grouped by concern so the cheap, frequently-run passes
* (depth/shadow/culling) only ever touch transform_/geometry_/streaming_ -
* those three sit contiguously at the front so they share the fewest cache
* lines, while the material-heavy texture_/extension_ groups (used only by
* the lighting passes) sit at the back.
*/
struct ModelStructuredBuffer
{
	ModelTransform transform_;
	ModelGeometry geometry_;
	ModelStreaming streaming_;
	ModelShading shading_;
	ModelSkining skining_;
	ModelMorph morph_;
	ModelTexture texture_;
	ModelExtension extension_;
};

StructuredBuffer<ModelStructuredBuffer> GetModelStructuredBuffer(uint index)
{
	return ResourceDescriptorHeap[index];
}

struct ModelShaderResourceIndices
{
	uint instance_index_;
	uint bone_matrix_index_;
	uint previous_bone_matrix_index_;
	uint morph_weight_index_;

	uint previous_morph_weight_index_;
	uint hi_z_index_;
	uint silhouette_index_;
	uint model_shader_resource_padding_0_;
};

/**
* [EN]
* Fur instances (ShadingModel::Fur) are appended to the shared instance
* buffer after opaque+transparent - fur_instance_offset_ is their start,
* fur_instance_count_ their count. Read by the shell-fur forward pass
* (FurShellAS -> FurShellMS -> FurShellPS).
*/
struct FurConstantBuffer
{
	uint fur_instance_offset_;
	uint fur_instance_count_;
	uint2 fur_padding_0_;
};

ConstantBuffer<FurConstantBuffer> GetFurConstantBuffer()
{
	return ResourceDescriptorHeap[constant_indices.fur_index_];
}

struct ModelCullingStructuredBuffer
{
	uint instance_index_;
	uint meshlet_index_;
	uint shell_index_;
	uint model_culling_structured_buffer_padding_0_;
};

StructuredBuffer<ModelCullingStructuredBuffer> GetModelCullingStructuredBuffer(uint index)
{
	return ResourceDescriptorHeap[index];
}

struct ModelCullingConstantBuffer
{
	uint single_sided_index_;
	uint double_sided_index_;
	uint arguments_index_;
	uint model_culling_constant_buffer_padding_0_;
};

ConstantBuffer<ModelCullingConstantBuffer> GetModelCullingConstantBuffer()
{
	return ResourceDescriptorHeap[dispatch_buffer_index_];
}

/**
* [EN]
* Dequantises a CompressedModelVertex with the instance's AABBs
* (instance.streaming_). Must stay in exact sync with the CPU encode in
* Crister.cpp (Upload).
*/
ExpandedModelVertex DecodeModelVertex(CompressedModelVertex packed, ModelStructuredBuffer instance)
{
	ExpandedModelVertex vertex;

	float3 position01 = float3(packed.position_xy_ & 0xFFFF, packed.position_xy_ >> 16, packed.position_z_texu_ & 0xFFFF) / 65535.0;
	vertex.position_ = instance.streaming_.position_min_ + position01 * instance.streaming_.position_extent_;

	float2 texcoord01 = float2(packed.position_z_texu_ >> 16, packed.texv_tangent_ & 0xFFFF) / 65535.0;
	vertex.texcoord_ = float2(instance.streaming_.texcoord_min_u_, instance.streaming_.texcoord_min_v_) + texcoord01 * instance.streaming_.texcoord_extent_;

	vertex.normal_ = OctNormalDecode(float2(packed.normal_ & 0xFFFF, packed.normal_ >> 16) / 65535.0);

	uint tangent_bits = packed.texv_tangent_ >> 16;
	float2 tangent_oct = float2(tangent_bits & 0xFF, (tangent_bits >> 8) & 0x7F) / float2(255.0, 127.0);
	float tangent_sign = (tangent_bits >> 15) ? 1.0 : -1.0;
	vertex.tangent_ = float4(OctNormalDecode(tangent_oct), tangent_sign);

	return vertex;
}

/**
* [EN]
* Unpacks a CompressedModelSkin's joints/weights.
*/
ExpandedModelSkin DecodeSkinVertex(CompressedModelSkin packed)
{
	ExpandedModelSkin skin;
	skin.joints_ = uint4(packed.joints_xy_ & 0xFFFF, packed.joints_xy_ >> 16, packed.joints_zw_ & 0xFFFF, packed.joints_zw_ >> 16);

	skin.weights_ = float4(packed.weights_ & 0xFF, (packed.weights_ >> 8) & 0xFF, (packed.weights_ >> 16) & 0xFF, packed.weights_ >> 24) / 255.0;
	skin.weights_ /= max(dot(skin.weights_, 1.0), 1e-6);
	return skin;
}

/**
* [EN]
* Rebuilds the row-vector-convention matrix (use as mul(vector, matrix)).
* The float4x4 vector constructor takes rows, so this is orientation-safe.
*/
float4x4 LoadBoneMatrix(ModelBoneMatrix bone)
{
	return float4x4(bone.row0_, bone.row1_, bone.row2_, bone.row3_);
}

/**
* [EN]
* Packs a triangle's Visibility-Buffer identity plus the interpolated
* texcoord: y reserves the low 7 bits for triangle_in_meshlet_index
* (meshlets emit at most 124 triangles, so 0..123 fits) and the remaining
* high bits for meshlet_index. zw carry the rasterized texcoord bit-for-bit
* (asuint, not a narrowing pack) so the lighting pass can sample material
* textures without re-deriving UVs - the source UVs are UNORM16 within the
* mesh's UV AABB, so any narrowing here would lose precision that tiled
* UVs (large texcoord_extent_) actually need.
*/
uint4 PackVisibilityID(uint instance_index, uint meshlet_index, uint triangle_in_meshlet_index, float2 texcoord)
{
	return uint4(instance_index, (meshlet_index << 7) | (triangle_in_meshlet_index & 0x7F), asuint(texcoord.x), asuint(texcoord.y));
}

/**
* [EN]
* Unpacks the instance/meshlet/triangle-in-meshlet fields packed by
* PackVisibilityID.
*/
void UnpackVisibilityID(uint4 packed, out uint instance_index, out uint meshlet_index, out uint triangle_in_meshlet_index)
{
	instance_index = packed.x;
	meshlet_index = packed.y >> 7;
	triangle_in_meshlet_index = packed.y & 0x7F;
}

/**
* [EN]
* Packs an RGBA color as four half-floats into a uint2 (8 bytes instead of
* the 16 a plain float4 costs) - used by the OIT fragment linked list
* (OITFragment::packed_color_rg_/packed_color_ba_), which holds many
* fragments per pixel and is worth shrinking.
*/
uint2 PackColor(float4 color)
{
	return uint2(f32tof16(color.r) | (f32tof16(color.g) << 16), f32tof16(color.b) | (f32tof16(color.a) << 16));
}

/**
* [EN]
* Unpacks a uint2 packed by PackColor back into an RGBA color.
*/
float4 UnpackColor(uint2 packed)
{
	return float4(f16tof32(packed.x & 0xFFFF), f16tof32(packed.x >> 16), f16tof32(packed.y & 0xFFFF), f16tof32(packed.y >> 16));
}

#endif // __MODEL_HLSL__
