<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\FoundationEngine\FoundationEngine.Csharp.csproj" Private="false" />
		<ProjectReference Include="..\AIEngine\AIEngine.Csharp.csproj" Private="false" />
		<ProjectReference Include="..\PhysicsEngine\PhysicsEngine.Csharp.csproj" Private="false" />
		<ProjectReference Include="..\AudioEngine\AudioEngine.Csharp.csproj" Private="false" />
		<ProjectReference Include="..\GraphicsEngine\GraphicsEngine.Csharp.csproj" Private="false" />
	</ItemGroup>
</Project>
