#pragma once
#include <FoundationEngine/Prelude.h>
#include <FoundationEngine/World/ECS/Entity/Entity.h>

namespace SeedCore
{
	/// [EN] Identifies a component type; points at the interned type-name string, so it is stable within the process and distinct per type.
	/// [JP] コンポーネント型を識別する ID。intern された型名の文字列を指すので、プロセス内で安定し、型ごとに異なる。
	using ComponentID = const void*;

	class InterfaceSparseSetStorage;

	/// [EN] Selects which storage strategy a component type uses: sparse-set (indirection, good for rare/optional components) or archetype-chunked (contiguous, good for common/frequently-iterated components).
	/// [JP] コンポーネント型が使用するストレージ戦略を選択する: スパースセット（間接参照、まれ/任意のコンポーネントに向く）またはアーキタイプ・チャンク構造化（連続配置、よく使われる/頻繁に走査されるコンポーネントに向く）。
	enum class ComponentStorage :Uint8
	{
		/// [EN] Stored in a SparseSet<T>, indexed by EntityID via indirection.
		/// [JP] SparseSet<T> に格納され、間接参照を介して EntityID でインデックスされる。
		SparseSet,

		/// [EN] Stored contiguously within an Archetype's Chunk, alongside every other component of entities sharing that archetype.
		/// [JP] Archetype の Chunk 内に連続配置される。同じアーキタイプを共有するエンティティの、他の全コンポーネントと共に格納される。
		Archetype,
	};

	/**
	* [EN]
	* Type-erased description of a component type, generated by
	* Component<T>::Metadata: its size/alignment, storage kind, and
	* type-erased construct/destruct/copy/move function pointers so the
	* ECS can manage instances of T without a compile-time-known type.
	*
	* ---------------------------------------------------------------------
	*
	* [JP]
	* コンポーネント型の型消去された記述。Component<T>::Metadata に
	* よって生成される。サイズ/アラインメント、ストレージ種別、および
	* 型消去された構築・破棄・コピー・ムーブ用の関数ポインタを持ち、
	* ECS がコンパイル時に型を知らずとも T のインスタンスを管理できる
	* ようにする。
	*/
	struct ComponentMetadata
	{
		/// [EN] Byte size of the component type.
		/// [JP] コンポーネント型のバイトサイズ。
		Size size_;

		/// [EN] Alignment requirement of the component type.
		/// [JP] コンポーネント型のアラインメント要件。
		Size alignment_;

		/// [EN] Which storage strategy this component type uses.
		/// [JP] このコンポーネント型が使用するストレージ戦略。
		ComponentStorage storage_;

		/// [EN] Type-erased default constructor: constructs a new instance in-place at the given address.
		/// [JP] 型消去されたデフォルトコンストラクタ: 指定されたアドレスへ新しいインスタンスをその場で構築する。
		void (*construct_)(void*);

		/// [EN] Type-erased destructor: destroys the instance at the given address.
		/// [JP] 型消去されたデストラクタ: 指定されたアドレスのインスタンスを破棄する。
		void (*destruct_)(void*);

		/// [EN] Type-erased copy constructor: constructs a copy of source in-place at dest.
		/// [JP] 型消去されたコピーコンストラクタ: source のコピーを dest へその場で構築する。
		void (*copy_)(void* dest, const void* source);

		/// [EN] Type-erased move constructor: move-constructs source's value into dest, then destroys source.
		/// [JP] 型消去されたムーブコンストラクタ: source の値を dest へムーブ構築し、その後 source を破棄する。
		void (*move_)(void* dest, void* source);

		/// [EN] Type-erased factory constructing this component's sparse-set storage; nullptr for archetype-stored components.
		/// [JP] このコンポーネントのスパースセットストレージを構築する、型消去されたファクトリ。アーキタイプ格納コンポーネントでは nullptr。
		ResourcePtr<InterfaceSparseSetStorage>(*createSparseStorage_)() = nullptr;

		/// [EN] For ComponentBehaviour-derived components: sets the component's world_/entity_ back-reference and binds each lifecycle function pointer (awake_/start_/tick_/...) the concrete type actually implements; nullptr otherwise.
		/// [JP] ComponentBehaviour 派生コンポーネント向け: コンポーネントの world_/entity_ 逆参照を設定し、具体的な型が実際に実装している各ライフサイクル関数ポインタ（awake_/start_/tick_/...）を束縛する。それ以外では nullptr。
		void (*setupLifecycle_)(void* component, void* world, Entity entity) = nullptr;

		/// [EN] Whether this component type derives from ComponentBehaviour.
		/// [JP] このコンポーネント型が ComponentBehaviour から派生しているかどうか。
		Bool isComponentBehaviour_ = false;

		/// [EN] Group label in the Add Component panel (e.g. "Light" for PointLight/SpotLight); set per registration by ComponentRegistry::Register, not by Metadata().
		/// [JP] Add Component パネルでの分類名(例: PointLight/SpotLight をまとめる "Light")。Metadata() ではなく、登録ごとに ComponentRegistry::Register が設定する。
		String category_;

		/// [EN] Module (HMODULE as an opaque pointer) whose REGISTER_COMPONENT made this entry, so the same header compiled into a downstream DLL (e.g. UserProject)
		///      never overwrites the engine's entry with function pointers that dangle after a hot reload. nullptr if the module could not be resolved.
		/// [JP] この登録を作った REGISTER_COMPONENT が属するモジュール(HMODULE を不透明なポインタで保持)。同じヘッダが下流の DLL(例: UserProject)に入っても、
		///      ホットリロード後に宙に浮く関数ポインタでエンジンの登録を上書きしないため。解決できなければ nullptr。
		void* owningModule_ = nullptr;
	};

	/**
	* [EN]
	* Fallback: any unspecialized T defaults to SparseSet storage.
	*
	* ---------------------------------------------------------------------
	*
	* [JP]
	* フォールバック: 特殊化されていない任意の T は、デフォルトで
	* SparseSet ストレージになる。
	*/
	template<typename T>
	struct ComponentTraits
	{
		/// [EN] The storage strategy T uses (overridden per type via SEED_TRAITS_SPEC, emitted by REGISTER_COMPONENT).
		/// [JP] T が使用するストレージ戦略（REGISTER_COMPONENT が生成する SEED_TRAITS_SPEC 経由で、型ごとに上書きされる）。
		static constexpr ComponentStorage storage = ComponentStorage::SparseSet;
	};

	/**
	* [EN]
	* Compile-time helper producing T's ComponentMetadata: captures T's
	* size/alignment and generates its type-erased construct/destruct/
	* copy/move function pointers via lambdas.
	*
	* ---------------------------------------------------------------------
	*
	* [JP]
	* T の ComponentMetadata を生成する、コンパイル時ヘルパー。T の
	* サイズ/アラインメントを捕捉し、ラムダ経由で型消去された
	* 構築・破棄・コピー・ムーブ用の関数ポインタを生成する。
	*/
	template<typename T>
	class Component
	{
	public:
		/**
		* [EN]
		* Returns T's compile-time-registered storage strategy.
		*
		* ---------------------------------------------------------------------
		*
		* [JP]
		* T のコンパイル時に登録されたストレージ戦略を返す。
		*/
		static constexpr ComponentStorage Storage()
		{
			return ComponentTraits<T>::storage;
		}

		/**
		* [EN]
		* Builds T's ComponentMetadata, tagged with the given storage kind.
		*
		* ---------------------------------------------------------------------
		*
		* [JP]
		* 指定されたストレージ種別でタグ付けされた、T の ComponentMetadata
		* を構築する。
		*/
		static constexpr ComponentMetadata Metadata(ComponentStorage storage)
		{
			return {
				sizeof(T), alignof(T), storage,
				[](void* ptr) { new(ptr) T(); },
				[](void* ptr) { static_cast<T*>(ptr)->~T(); },
				[](void* dest, const void* source) { new(dest) T(*static_cast<const T*>(source)); },
				[](void* dest, void* source) { new(dest) T(std::move(*static_cast<T*>(source))); static_cast<T*>(source)->~T(); }
			};
		}

		/**
		* [EN]
		* Builds T's ComponentMetadata using its compile-time-registered
		* storage strategy (ComponentTraits<T>::storage).
		*
		* ---------------------------------------------------------------------
		*
		* [JP]
		* T のコンパイル時に登録されたストレージ戦略
		* （ComponentTraits<T>::storage）を使用して、T の
		* ComponentMetadata を構築する。
		*/
		static constexpr ComponentMetadata Metadata()
		{
			return Metadata(ComponentTraits<T>::storage);
		}
	};
}
